### ISSUE TITLE
Build devkitPro

### ISSUE THREAD

**Issue by phase** [felix-lang/fbuild#18]
Fbuild can't build devkitPro projects?!

**Comment by kirbyfan64** [comment]
It *should*. You just need to pass the devkitPro compiler path to `guess_static` or `guess_shared`:

```python
guess_static(..., exe='path/to/devkit/pro/compiler')
```

Usually, though, you'll end up reading this option from a comnand-line options, like [unmangler does](https://github.com/kirbyfan64/unmangler/blob/master/fbuildroot.py).

**Comment by kirbyfan64** [comment]
@phase Can this be closed now?

**Comment by phase** [comment]
I have no idea, and I'm not in a position to test it right now. Probably yes.

**Comment by kirbyfan64** [comment]
@phase I'll just close this now. Trying to reduce the issue count. :D
