### ISSUE TITLE
No control over link order

### ISSUE THREAD

**Issue by g2p** [felix-lang/fbuild#19]
I'm building and linking a C++ program.
If I build it manually I can put the -l flags last (one of them is an ar archive), and things build correctly.
If I use `cflags` and `lflags`, the .os file appears after the -l flags, and I get undefined symbols.
I think you should change the default order of g++ arguments.

**Comment by kirbyfan64** [comment]
Ok, so, technically you're supposed to use `external_libs` argument, not `lflags`, for libraries. HOWEVER, some tools (like pkg-config) mix link flags with libraries, so you're definitely correct in that the flags need to be *after* the inputs.

**Comment by skaller** [comment]
> On 28 Sep 2015, at 04:14, Ryan Gonzalez <notifications@github.com> wrote:
> 
> Ok, so, technically you're supposed to use external_libs argument, not lflags, for libraries. HOWEVER, some tools (like pkg-config) mix link flags with libraries, so you’re definitely correct in that the flags need to be after the inputs.

How do I get fbuild to add /DEBUG after /link?


—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by kirbyfan64** [comment]
@skaller What exactly do you mean?

**Comment by skaller** [comment]
What exactly do you mean by that? I rarely ever use MSVC...

On Sun, Sep 27, 2015 at 4:54 PM, john skaller <skaller@users.sourceforge.net
> wrote:

>
> > On 28 Sep 2015, at 04:14, Ryan Gonzalez <notifications@github.com>
> wrote:
> >
> > Ok, so, technically you're supposed to use external_libs argument, not
> lflags, for libraries. HOWEVER, some tools (like pkg-config) mix link flags
> with libraries, so you’re definitely correct in that the flags need to be
> after the inputs.
>
> How do I get fbuild to add /DEBUG after /link?
>
>
> —
> john skaller
> skaller@users.sourceforge.net
> http://felix-lang.org
>
> --
> You received this message because you are subscribed to the Google Groups
> "Felix Language" group.
> To unsubscribe from this group and stop receiving emails from it, send an
> email to felix-language+unsubscribe@googlegroups.com.
> To post to this group, send email to felix-language@googlegroups.com.
> Visit this group at http://groups.google.com/group/felix-language.
> For more options, visit https://groups.google.com/d/optout.
>



-- 
Ryan
[ERROR]: Your autotools build scripts are 200 lines longer than your
program. Something’s wrong.
http://kirbyfan64.github.io/

**Comment by g2p** [comment]
Looking at pkg-config usage in another project (https://github.com/g2p/bcache-tools/blob/HEAD/Makefile), pkg-config --libs goes into LDLIBS, which is listed after the source file.
The positions of lflags and external_libs seem to match LDFLAGS and LDLIBS respectively in GNU make's implicit rules, but for pkg-config compatibility you'd need to allow arbitrary flags in LDLIBS.

**Comment by skaller** [comment]
> On 28 Sep 2015, at 08:08, Ryan Gonzalez <notifications@github.com> wrote:
> 
> @skaller What exactly do you mean?

In order to produce *.pdb debug database on Windows, two things have
to be done: when compiling set /Zi, and when linking set /DEBUG.
I have added /Zi to the compiles. But I don’t know how to add /DEBUG
to the links. If linking with cl.exe it looks like

	cl.exe objfiles … /link /DEBUG ….

The /DEBUG has to come after the /link switch, cl.exe passes it to /link.exe.

https://msdn.microsoft.com/en-us/library/xe4t6fc1.aspx

https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx

https://msdn.microsoft.com/en-us/library/958x11bc.aspx

MSDN says /Zi implies /debug, I can’t find that option, I assume
they meant /DEBUG. Some things are case sensitive, MS is a mess here.
For example /LINK on cl.exe command line does not work, you have to use
lower case /link. Grrr.

In any case using fbuild to build Felix at the moment I am getting
*.pdb files for the toolchain objects, but not any of the RTL objects
or libraries nor for bootflx (which is the program i have to debug).


—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org

**Comment by g2p** [comment]
So as far as my simple needs are concerned, external_libs is enough for me.
For pkg-config support, /debug support, etc, LDFLAGS/lflags needs to stay before the source file because it's where you'd set something like -Wl,--as-needed; don't move anything, but consider adding an LDLIBS/ldlibs parameter that takes arbitrary flags and goes after external_libs.

**Comment by kirbyfan64** [comment]
@g2p So, `ldlibs` should work for your use case. Note that it does *not* work on Windows yet like @skaller needs, so I'm leaving this open until then. Next time you have any trouble, feel free to drop by the [mailing list](https://groups.google.com/forum/#!forum/fbuild)!

**Comment by kirbyfan64** [comment]
@skaller Now it works!! :)

**Comment by skaller** [comment]
> On 28 Sep 2015, at 10:57, Ryan Gonzalez <notifications@github.com> wrote:
> 
> @g2p So, ldlibs should work for your use case. Note that it does not work on Windows yet like @skaller needs, so I'm leaving this open until then. Next time you have any trouble, feel free to drop by the mailing list!
> 

Actually, I added

	link_flags :  [‘/DEBUG’],

to the overrides in fbuildroot.py and that actually does propagate it seems!
I got weird errors when I forgot the [] though. Dynamic typing sucks :-)


—
john skaller
skaller@users.sourceforge.net
http://felix-lang.org
