### ISSUE TITLE
git clone through http://

### ISSUE THREAD

**Issue by userxfce** [felix-lang/fbuild#3]
Hello,

 I am behind a proxy and cannot use the git:// protocol on github.com. So I am using this workaround: http://rip747.wordpress.com/2008/09/12/git-clone-over-http-who-knew/
 So, when typing:
git clone http://github.com/defunkt/facebox.git
 everything works flawless (and no username/password are required). But, when typing:
git clone http://github.com/erickt/fbuild.git
 an username/password are required. Neither the username/password for my proxy, neither my username/password for my github.com account work.

**Comment by kirbyfan64** [comment]
@axeoth I think it's supposed to be `git clone https://github.com/felix-lang/fbuild.git`. Notice the difference between `felix-lang` and `erickt`.

**Comment by axeoth** [comment]
Hay, thank you! Indeed. Silly me.
