### ISSUE TITLE
color output

### ISSUE THREAD

**Issue by axeoth** [felix-lang/fbuild#5]
Hello,

 There is some tool called colorgcc trying to colorize the output of the gcc compiler. Clang allows colorized output, however gcc does not.

http://schlueters.de/colorgcc.html

 Is there a builder defined for the c and cxx languages in fbuild?

 colorgcc is command-line compatible with gcc and g++, so the following solution works:

http://blog.emptycrate.com/node/429

(
cd /usr/local/bin
sudo ln -s /usr/bin/colorgcc gcc
sudo ln -s /usr/bin/colorgcc g++
sudo ln -s /usr/bin/colorgcc cc
sudo ln -s /usr/bin/colorgcc c++
)

Thanks.

**Comment by kirbyfan64** [comment]
@axeoth You can pass a custom executable to `guess_*`:

```python
c = guess_static(ctx, exe='colorgcc')
```

**Comment by kirbyfan64** [comment]
@axeoth Actually, I'm reopening this because compiler detection isn't yet implemented and the example I gave you is going to end up being identified as `clang`.

**Comment by kirbyfan64** [comment]
Fixed by 1ab065e7fb49436a8f6420cdf229eaaff1a9a5ae.

**Comment by axeoth** [comment]
Great! Thanks!
